.github/workflows/NodeJS.yml
Make the GitHub workflows green.
I commented out (rather than removed) most of the workflows, because I expect we'll bring some of them back, in particular the Linux and Windows runs, once they're supported.
I added some steps to build and test the current implementation, on the two variants of OS X and three currently supported versions of Node. Each of these 6 jobs runs in under a minute.
=> fix workflows

README.md, bindings/scripts/fetch_libduckdb_linux.py, bindings/scripts/fetch_libduckdb_mac.py, bindings/scripts/fetch_libduckdb_win.py, bindings/test/constants.test.ts
No C API changes going from v1.1.1 -> v1.1.2, except for one addition of `const` that doesn't affect these bindings.
All tests pass; no other changes needed.
=> upgrade duckdb to v1.1.2

api/src/DuckDBVector.ts, api/test/api.test.ts
- Implement varint conversion from bytes to bigint
- Fix type of timestamp_tz vector
=> api: implement varint, fix timestamp_tz vector type

api/src/enums.ts, api/test/api.test.ts
A couple enums were being exported as types, but not values, from the API. Fixed this and wrote a couple tests.
=> fix api enum export

api/src/DuckDBInstance.ts
When using JS (instead of TS), it's not uncommon to try to set config options to non-string values (such as numbers). This results in an error. Convert the values to strings to allow this case and avoid the error.
=> convert config values to string

README.md, api/pkgs/@duckdb/node-api/README.md, bindings/pkgs/@duckdb/node-bindings-darwin-arm64/README.md, bindings/pkgs/@duckdb/node-bindings-linux-x64/README.md, bindings/pkgs/@duckdb/node-bindings-win32-x64/README.md, bindings/pkgs/@duckdb/node-bindings/README.md
- Add documentation to @duckdb/node-api README.
- Add basic explanation plus links to other packages.
- Update repo README to contain links to package docs plus development documentation.
=> update all READMEs

api/src/DuckDBType.ts, api/src/DuckDBVector.ts, api/src/conversion/dateTimeStringConversion.ts, api/src/conversion/displayStringForDuckDBValue.ts, api/src/conversion/stringFromBlob.ts, api/src/conversion/stringFromDecimal.ts, api/src/values/DuckDBArrayValue.ts, api/src/values/DuckDBBitValue.ts, api/src/values/DuckDBBlobValue.ts, api/src/values/DuckDBDateValue.ts, api/src/values/DuckDBDecimalValue.ts, api/src/values/DuckDBIntervalValue.ts, api/src/values/DuckDBListValue.ts, api/src/values/DuckDBMapValue.ts, api/src/values/DuckDBStructValue.ts, api/src/values/DuckDBTimeTZValue.ts, api/src/values/DuckDBTimeValue.ts, api/src/values/DuckDBTimestampMillisecondsValue.ts, api/src/values/DuckDBTimestampNanosecondsValue.ts, api/src/values/DuckDBTimestampSecondsValue.ts, api/src/values/DuckDBTimestampTZValue.ts, api/src/values/DuckDBTimestampValue.ts, api/src/values/DuckDBUUIDValue.ts, api/src/values/DuckDBUnionValue.ts, api/test/api.test.ts
- Change structure of value several value objects, including ARRAY and LIST to be JS arrays instead of vectors, and STRUCT to be a JS object.
- Add toString implementations to all values, including date, time, timestamp(s), interval, decimal, blob, bit, and uuid.
- Fix a bug in reading bools from a bit value.
- Add Min and Max value constants to primitive type classes and non-primitive value classes.
- Remove generic type argument from array and list vectors.
- Use the above to simplify the API unit tests.
- Add unit tests for toString implementations.
=> change nested value structure; add toString to all values

api/pkgs/@duckdb/node-api/README.md, api/src/DuckDBAppender.ts, api/src/DuckDBLogicalType.ts, api/src/DuckDBResult.ts, api/src/DuckDBType.ts, api/src/DuckDBVector.ts, bindings/test/utils/expectChunk.ts, bindings/test/utils/expectResult.ts, bindings/test/utils/withLogicalType.ts
- Support `alias` on DuckDBTypes, and pass through alias when creating them from DuckDBLogicalTypes.
- Remove `dispose` calls from API README, and add bit about how to consume the JSON type (by checking the alias).
=> logical type alias and cleanup

api/pkgs/@duckdb/node-api/README.md, api/src/DuckDBVector.ts, api/src/index.ts, api/src/values/DuckDBDateValue.ts, api/src/values/DuckDBDecimalValue.ts, api/src/values/DuckDBTimeTZValue.ts, api/src/values/DuckDBTimeValue.ts, api/src/values/DuckDBTimestampTZValue.ts, api/src/values/DuckDBTimestampValue.ts, api/test/api.test.ts
- Add methods to some value types (Date, Time[TZ], Timestamp[TZ], Decimal) to convert from and to primitive values.
- Expose some primitive-to-primitive conversion functions from the bindings.
- Rename a few parameters and add some doc comments.
- Add some unit tests for new API functions.
=> value conversion in api

api/pkgs/@duckdb/node-api/README.md, api/src/DuckDBDataChunk.ts, api/src/DuckDBResult.ts, api/test/api.test.ts, api/test/bench/util/runSql.ts
- Add some convenience functions for getting information out of results.
- Add tests and update README.
=> result convenience functions

api/pkgs/@duckdb/node-api/README.md, api/src/DuckDBConnection.ts, api/src/DuckDBDataChunk.ts, api/src/DuckDBPendingResult.ts, api/src/DuckDBPreparedStatement.ts, api/src/DuckDBResult.ts, api/src/DuckDBResultReader.ts, api/test/api.test.ts
- Add a "result reader" helper that makes consuming multi-chunk results easier.
- Add entry points that construct a reader.
- Add helpers to extract all the values of a result in column-major or row-major form.
- Cache vectors in DuckDBResult.
- Add docs to README.
=> result reader

api/src/values/DuckDBUUIDValue.ts, api/test/api.test.ts
Fix a bug in DuckDBUUIDValue.toString where the MSB wasn't being flipped before display. DuckDB UUID values are stored with the MSB flipped so that numeric ordering matches string ordering.
Also fixed the tests to actually compare the correct values. (This mistake in the tests covered up the mistake in the code, unfortunately.)
=> fix uuid toString

api/pkgs/@duckdb/node-api/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-x64/package.json, bindings/pkgs/@duckdb/node-bindings-win32-x64/package.json, bindings/pkgs/@duckdb/node-bindings/package.json, bindings/scripts/fetch_libduckdb_linux.py, bindings/scripts/fetch_libduckdb_mac.py, bindings/scripts/fetch_libduckdb_win.py, bindings/test/constants.test.ts
No changes to C API. No code changes to bindings or API needed. Keeping Neo version at alpha.4
=> upgrade to duckdb 1.1.3 and bump pkg versions

api/src/DuckDBInstance.ts, api/test/api.test.ts, bindings/src/duckdb_node_bindings.cpp, bindings/test/config.test.ts
In both the bindings and the api layers, set a (different) default value for the `duckdb_api` config.
Ensure this works whether or not the user provides an explicit config; if they do, ensure it's overridable.
The default `duckdb_api` value for the bindings layer is: `node-neo-bindings`
The default for the api layer (which most people will use) is: `node-neo-api`
=> default duckdb_api config

.github/workflows/DuckDBNodeBindingsAndAPI.yml, README.md, api/pkgs/@duckdb/node-api/README.md, bindings/binding.gyp, bindings/package.json, bindings/pkgs/@duckdb/node-bindings-linux-arm64/.npmrc, bindings/pkgs/@duckdb/node-bindings-linux-arm64/README.md, bindings/pkgs/@duckdb/node-bindings-linux-arm64/package.json, bindings/pkgs/@duckdb/node-bindings/README.md, bindings/pkgs/@duckdb/node-bindings/package.json, bindings/scripts/fetch_libduckdb_linux_aarch64.py, pnpm-lock.yaml
- Add support for Linux arm64.
- The linux arm64 binaries are built using cross-compilation on a linux x64 runner. The tests are not run (since the can't on that architecture). If/when standard linux arm64 runners become available, we could switch to those.
- I had to remove some of the fine-grained control over publishing individual packages, since workflow_dispatch has a limit of 10 input parameters. Perhaps they could be brought back, if needed, by splitting the workflow. But I've never used them independently.
=> build linux arm64

api/test/bench/write.bench.ts
This PR adds some simple write benchmarks, comparing insert vs appender performance at batches of 1 and 1000.
(These numbers are taken on my M1 Macbook Pro)
```
✓ test/bench/write.bench.ts (4) 3999ms
✓ batch write of size 1 (2) 1283ms
name                  hz     min     max    mean     p75     p99    p995    p999     rme  samples
· 1 insert bind   4,440.54  0.1670  9.4687  0.2252  0.2373  0.3399  0.4004  1.2738  ±4.50%     2221
· 1 row append   34,196.13  0.0257  1.6729  0.0292  0.0294  0.0408  0.0477  0.0725  ±0.98%    17099   fastest
✓ batch write of size 1000 (2) 2715ms
name                    hz     min     max    mean     p75     p99    p995    p999      rme  samples
· 1000 insert bind    7.4680  122.09  174.06  133.90  129.36  174.06  174.06  174.06  ±10.23%       10
· 1000 row …
```
=> Simple write benchmarks

api/pkgs/@duckdb/node-api/README.md
Specifically this part:
```
Read chunk data (row-major):
const columns = chunk.getRows(); 
```
^ Variable name should be `rows`, not columns.
=> Minor doc fix related to node-api docs

api/pkgs/@duckdb/node-api/README.md, api/src/DuckDBConnection.ts, api/src/DuckDBMaterializedResult.ts, api/src/DuckDBPendingResult.ts, api/src/DuckDBPreparedStatement.ts, api/src/DuckDBResult.ts, api/src/DuckDBResultReader.ts, api/src/DuckDBVector.ts, api/src/createResult.ts, api/src/index.ts, api/test/api.test.ts, api/test/bench/util/runSql.ts, bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts, bindings/src/duckdb_node_bindings.cpp, bindings/test/appender.test.ts, bindings/test/config.test.ts, bindings/test/extracted_statements.test.ts, bindings/test/pending.test.ts, bindings/test/prepared_statements.test.ts, bindings/test/query.test.ts, bindings/test/utils/ExpectedResult.ts, bindings/test/utils/ExpectedVector.ts, bindings/test/utils/expectResult.ts, bindings/test/utils/expectValidity.ts, bindings/test/utils/expectVector.ts, bindings/test/utils/expectedVectors.ts, bindings/test/utils/getValue.ts, bindings/test/utils/isValid.ts
Implement several "deprecated" C API functions related to result streaming. While these are deprecated, the functionality they expose is likely to continue to exist in some form in the future.
New functions:
- `row_count`
- `result_get_chunk`
- `result_is_streaming`
- `result_chunk_count`
- `execute_prepared_streaming`
- `pending_prepared_streaming`
Also add `null` as a possible type to some existing C API type definitions (because the underlying function can return null):
- The `validity` argument to `validity_row_is_valid`.
- The result of `fetch_chunk`.
=> result streaming

api/src/DuckDBConnection.ts, api/test/api.test.ts, bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts, bindings/src/duckdb_node_bindings.cpp, bindings/test/connection.test.ts
Implement `connection.disconnect()` (and the synonym `connection.close()`).
The challenge was dealing with the automatic disconnect during finalization and also double-disconnect. To make this work I had to add another layer of indirection around the connection object, so it can be nulled out. Luckily this wasn't too bad.
Added some error handling with helpful exception messages for trying to do things (query, prepare, etc.) on a disconnected connection. Some C API functions don't initialize their out parameters in some error conditions, so I added some defense-in-depth against that. Added several unit tests, at both the bindings and api layers.
=> disconnect

api/pkgs/@duckdb/node-api/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-x64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-x64/package.json, bindings/pkgs/@duckdb/node-bindings-win32-x64/package.json, bindings/pkgs/@duckdb/node-bindings/package.json
This version contains:
- Support for [result streaming](https://github.com/duckdb/duckdb-node-neo/pull/77).
- Support [explicit disconnect](https://github.com/duckdb/duckdb-node-neo/pull/78).
=> bump pkgs to 1.1.3-alpha.8

api/test/bench/read.bench.ts
This PR adds some benchmarks to compare the following queries:
- selecting a range of rows
- performing a series of aggregations across a range of rows
- performing a series of rolling window aggregations across a range of rows
and the following execution strategies:
Measuring 'Time to First Row'
- runAndReadUntil(q, 1)                    
- start runTask pending.readUntil(1)       
- start runTask single fetchChunk          
- streamAndReadUntil(q, 1)                 
- startStream runTask pending.readUntil(1) 
- startStream runTask single fetchChunk    
- run single fetchChunk                    
- stream single fetchChunk                     
Measuring 'Time to Full Result'
- runAndReadAll()                        
- start runTask pending.readAll()        
- start runTask fetchChunks …
=> Read benchmarks

api/test/bench/prepare.bench.ts
This PR adds a benchmark to compare the performance of parameterising a query.
The statistically significant takeaway by my reading is:
- It's faster to `prepare` once then re-bind parameters multiple times if possible.
- If the query can't be parameterised, calling `prepare` and binding every time has an overhead that can be avoided with a simpler `run` call.
````
✓ test/bench/prepare.bench.ts (3) 2041ms
✓ Parameterised queries (3) 2040ms
name                        hz     min     max    mean     p75     p99    p995    p999     rme  samples
· Multiple queries      2,634.62  0.2616  5.2889  0.3796  0.3935  0.5699  0.6606  4.9380  ±2.84%     1318
· Prepared with re-use  2,908.72  0.2303  5.0928  0.3438  0.3634  0.5307  0.5631  4.3680  ±2.58%     1455   fastest
· Prepared each time …
```
=> Parameterised query benchmark

api/pkgs/@duckdb/node-api/README.md, api/src/DuckDBDataChunk.ts, api/src/DuckDBType.ts, api/src/DuckDBVector.ts, api/src/conversion/bytesFromString.ts, api/src/values/DuckDBBlobValue.ts, api/test/api.test.ts, api/test/util/testAllTypes.ts, bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts, bindings/src/duckdb_node_bindings.cpp, bindings/test/data_chunk.test.ts
- Support writing to vectors of all types.
- Add convenience methods for writing to data chunks.
- Add convenience methods for creating types, as well as convenience getters for important values of each type.
- Add way to get a DuckDBLogicalType from a DuckDBType.
- Refactor data for test_all_types so it can be shared with appender tests.
- Add many tests for writing vectors, data chunks, and appending data chunks, including an "append all data types" test.
- To support the above, add two new functions to the bindings layer, for writing data to vector and validity buffers.
=> support writing to data chunks

api/pkgs/@duckdb/node-api/README.md, api/src/DuckDBPreparedStatement.ts, api/src/DuckDBVector.ts, api/src/typeForValue.ts, api/test/api.test.ts
Add a `bind` convenience method to DuckDBPreparedStatement, that can take either an array or object of parameters, and can optional take an array or object of types. If no types are provided, the types will be inferred.
=> bind helper

api/src/DuckDBVector.ts, api/test/api.test.ts
Add some logic to DuckDBListVector to handle writes to nested list vectors, but delegating to the parent. This is necessary because updates can change the length of the child vector, necessitating updates to the other lists in the parent vector. Added a test to verify the behavior.
=> handle nested list vector updates

api/src/DuckDBDataChunk.ts, api/src/DuckDBResult.ts, api/src/DuckDBResultReader.ts, api/src/getColumnsFromChunks.ts, api/src/getRowsFromChunks.ts
Factor out some common code and add some "visit" methods and additional row getters to DuckDBDataChunk.
=> refactor result extraction to use visitors

api/src/DuckDBDataChunk.ts, api/src/DuckDBResult.ts, api/src/DuckDBResultReader.ts, api/src/getColumnsFromChunks.ts, api/src/getColumnsObjectFromChunks.ts, api/src/getRowObjectsFromChunks.ts, api/src/getRowsFromChunks.ts, api/test/api.test.ts
Implement `getRowObjects` and `getColumnsObject` on `DuckDBResult` and `DuckDBResultReader`, along with supporting function `deduplicatedColumnNames` on both.
=> row and column objects

api/src/DuckDBConnection.ts, api/src/DuckDBPreparedStatement.ts, api/src/typeForValue.ts, api/test/api.test.ts
Two improvements to bind type inference & specification:
- If a number value has no fractional part, infer INTEGER instead of DOUBLE.
- Allow explicitly type specification by name to only contain some types (and infer the rest).
=> bind type inference improvements

api/src/DuckDBDataChunk.ts, api/src/DuckDBResult.ts, api/src/DuckDBResultReader.ts, api/src/DuckDBType.ts, api/src/DuckDBValueConverter.ts, api/src/DuckDBValueToJsonConverter.ts, api/src/convertColumnsFromChunks.ts, api/src/convertColumnsObjectFromChunks.ts, api/src/convertRowObjectsFromChunks.ts, api/src/convertRowsFromChunks.ts, api/src/index.ts, api/test/api.test.ts, api/test/util/testAllTypes.ts
Add several new helpers for getting result data as JSON-serializable values.
Both DuckDBResult and DuckDBResultReader now have `getColumnsJson`, `getColumnsObjectJson`, `getRowsJson`, and `getRowObjectsJson`.
The conversion to JSON-serializable values is non-lossy. DuckDB data values that cannot be expressed in JSON are usually converted to a string; in a few cases (e.g. INTERVAL, MAP, UNION) they're converted to an object or array.
This is implemented using a general-purpose value conversion mechanism, which is exposed on DuckDBDataChunk. Other conversions can be implemented using this mechanism.
=> json result helpers

api/pkgs/@duckdb/node-api/README.md
Add sections about new features to README:
- Type inference for binding.
- Various methods for getting data.
- JSON conversion.
=> readme updates

api/pkgs/@duckdb/node-api/README.md
Add a few new sections to the README for @duckdb/node-api:
- A bit about TIMESTAMP_TZ string conversion and how to set the timezone used.
- A couple sections listing and briefly describing the many ways to run SQL and get result data.
=> api README additions

api/pkgs/@duckdb/node-api/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-x64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-x64/package.json, bindings/pkgs/@duckdb/node-bindings-win32-x64/package.json, bindings/pkgs/@duckdb/node-bindings/package.json
- Result data extraction conveniences, including row & column objects & json.
- Better type inference when binding parameters, including relaxing the need to specify all types (or none).
- Full implementation of `toString` for TIMESTAMP_TZ and TIME_TZ.
- Many additions to README.
=> bump pkgs to 1.1.3-alpha.10

api/src/DuckDBLogicalType.ts
Older versions of TypeScript (than 5.1) require that the type of a `get` accessor be assignable to the type of the corresponding `set` accessor. Because the type of `set` accessor for `DuckDBLogicalType.alias` did not include `undefined`, it triggered a compiler error for these older TS versions. It's trivial to support these older versions by accepting `undefined` (or `null`) and treating it the same as the empty string, which matches the same behavior as the underlying C API function.
See https://github.com/duckdb/duckdb-node-neo/issues/120
=> accept null or undefined for logical type alias

bindings/src/duckdb_node_bindings.cpp, bindings/test/data_chunk.test.ts, bindings/test/logical_type.test.ts, bindings/test/prepared_statements.test.ts, bindings/test/values.test.ts
Fix for https://github.com/duckdb/duckdb-node-neo/issues/128.
When creating struct, list, or array values, or struct, union, or enum types, or data chunks, special handling is needed when empty arrays are provided. The underlying C API functions need valid data pointers even though the supplied count is zero.
Added unit tests for all relevant cases.
=> fix empty nested values and types

api/pkgs/@duckdb/node-api/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-x64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-x64/package.json, bindings/pkgs/@duckdb/node-bindings-win32-x64/package.json, bindings/pkgs/@duckdb/node-bindings/package.json
Two fixes, for https://github.com/duckdb/duckdb-node-neo/issues/120 and https://github.com/duckdb/duckdb-node-neo/issues/128.
=> bump pkgs to 1.1.3-alpha.11

bindings/pkgs/@duckdb/node-bindings/duckdb.js
Proposal to fix: https://github.com/duckdb/duckdb-node-neo/issues/126
Before this change, the loading of node js binary was fully dynamic. 
The proposed way to do this is to explicitly define all binaries that could be loaded. That helps framework that applies tracing on node_modules such as nextjs (when deployed as lambda or standalone) to detect that the binary is in use.  It also allows to set a custom message indicating the reason of error.
There's many other ways to achieve the same idea (see esbuild, or sharp with require.resolve), this one keeps the loading as simple possible.
Happy to discuss if it makes sense
=> feat: explicit loading of native binaries

.github/workflows/DuckDBNodeBindingsAndAPI.yml, api/src/createValue.ts, api/test/api.test.ts, bindings/src/duckdb_node_bindings.cpp, bindings/test/values.test.ts
Fix for second part of https://github.com/duckdb/duckdb-node-neo/issues/128.
The C API returns `nullptr` when attempting to create a value of a nested type with a item or entry type of ANY. Note that `nullptr` is distinct from a `duckdb_value` representing a SQL NULL value; we don't want `duckdb_value` to ever be `nullptr`. So, we need to fail gracefully in this case, by throwing an exception.
In the Node Neo API, when binding values to prepared statements, the user might leave the type unspecified in a way that we can't infer (such as by passing an empty array), or they might explicitly specify the ANY type. In either case, we can end up with an ANY type (failed inference returns ANY). Rather than let the generic low-level exception through, we detect these cases and throw an error with …
=> handle ANY type in nested values

.github/workflows/DuckDBNodeBindingsAndAPI.yml, bindings/src/duckdb_node_bindings.cpp
Fix a crash caused by destroying the `logical_type` returned by `get_value_type` in the finalizer for the returned External. Apparently, unlike all other `logical_type`s returned by the C API, this one must not be explicitly destroyed; it's tied to the lifetime of the value.
This was the cause of the frequent but inconsistent failures in the bindings tests for Windows. Probably it was only happening on Windows and not the other platforms due to timing differences. I re-enabled the Windows tests.
=> fix crash on finalization for logical_type from get_value_type

bindings/src/duckdb_node_bindings.cpp, bindings/test/prepared_statements.test.ts
Fix a seg fault that can occur a C API function returns an error without creating a result. We need to initialize the result's internal data to `nullptr`, and also handle when `duckdb_result_error` returns `nullptr`. See https://github.com/duckdb/duckdb-node-neo/issues/142 for the scenario in which this was discovered.
It's hard to add a unit test for this because the known case where this can occur is nondeterministic. I added a test that I used to manually repro and verify the fix, but it's skipped by default because of the nondeterminism.
=> guard against null errors

bindings/src/duckdb_node_bindings.cpp, bindings/test/prepared_statements.test.ts
Use the `_length` variants of C API functions that take C strings where possible, to handle embedded null characters properly. This was visible through the API in at least one case (binding VARCHARs with embedded nulls). Added a test for this case.
Also update the `param_type` tests now that it works in more cases. But I found a new bug in 1.2.0, where `param_type` returns INVALID for VARCHARs (only). I've confirmed this is a bug in DuckDB and am filing an issue there.
=> fix binding strings with nulls; update param type tests

bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts, bindings/src/duckdb_node_bindings.cpp
Add comment placeholders for all new C API functions added in 1.2.0 and update function accounting comment.
Validated with `checkFunctionSignatures` script.
=> add comment placeholders for new C API functions in 1.2.0

api/src/DuckDBType.ts, api/src/DuckDBVector.ts, api/src/values/DuckDBTimestampMillisecondsValue.ts, api/src/values/DuckDBTimestampNanosecondsValue.ts, api/src/values/DuckDBTimestampSecondsValue.ts, api/src/values/DuckDBTimestampTZValue.ts, api/src/values/DuckDBTimestampValue.ts, api/test/api.test.ts, bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts, bindings/src/duckdb_node_bindings.cpp, bindings/test/conversion.test.ts
- Add support for is_finite_timestamp_s, is_finite_timestamp_ms, and is_finite_timestamp_ns.
- Add corresponding bindings types, and change API types to match.
- Add pos/neg inf constants for relevant types.
- Add tests in both bindings and API layers.
=> is_finite for non-standard timestamps

api/src/DuckDBPreparedStatement.ts, api/test/api.test.ts, bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts, bindings/src/duckdb_node_bindings.cpp
Adding binding for `param_logical_type` and also corresponding `parameterType` on `DuckDBPreparedStatement`. Add some API tests for it. Note that https://github.com/duckdb/duckdb/issues/16137 currently causes it to report the wrong type for VARCHAR parameters.
=> support param_logical_type

api/src/DuckDBPreparedStatement.ts, api/src/createValue.ts, api/test/api.test.ts, bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts, bindings/src/duckdb_node_bindings.cpp, bindings/test/values.test.ts
Also fix a typo in `createValue` (a duplicate UNION case should have been BIT) and restructure the API-level param binding test to be more general and flexible.
=> bind non-standard timestamps

api/src/DuckDBPreparedStatement.ts, api/src/DuckDBVector.ts, api/src/createValue.ts, api/src/values/DuckDBUUIDValue.ts, api/test/api.test.ts, bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts, bindings/src/duckdb_node_bindings.cpp, bindings/test/values.test.ts
Also add a couple utility functions to `DuckDBUUIDValue` to aid correct conversions to and from JS BigInts.
=> uuid type: create, get, and bind

api/pkgs/@duckdb/node-api/README.md, api/src/DuckDBConnection.ts, api/test/api.test.ts, api/test/bench/read.bench.ts, api/test/bench/write.bench.ts, bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts, bindings/src/duckdb_node_bindings.cpp, bindings/test/appender.test.ts
Add support for `create_appender_ext`, which allows specifying the catalog (aka database) name. Also change `create_appender` to support the schema being optional (null).
I made a minor breaking change to the API: I reversed the order of the arguments to `createAppender` in order to make the schema and catalog names optional. This allows for simpler calls when the current database/catalog and/or default schema is desired.
I changed all call sites in the tests and in the main README.
I lowered the iterations for the `read` benchmark because it was taking too long.
=> create appender ext

api/src/DuckDBAppender.ts, api/src/DuckDBVector.ts, api/src/createValue.ts, api/test/api.test.ts, bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts, bindings/src/duckdb_node_bindings.cpp, bindings/test/appender.test.ts, bindings/test/values.test.ts
Add support for `append_value` and use it to implement most of the rest of the appender functions. (MAP and UNION still don't have value-creation functions in the C API.)
Also found and fixed a bug with conversion between hugeints and JS BigInts.
=> append value

api/pkgs/@duckdb/node-api/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-x64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-x64/package.json, bindings/pkgs/@duckdb/node-bindings-win32-x64/package.json, bindings/pkgs/@duckdb/node-bindings/package.json
Version notes:
- Binding most types to parameters is now supported. The only remaining unsupported types are MAP and UNION; these still need C API support for creating values (see this [PR](https://github.com/duckdb/duckdb/pull/14613)).
- Appending most types row-by-row is now supported. MAP and UNION are not yet supported for the same reason as above.
- Added support for specifying the database/catalog name when creating an appender. (Support for this was added to the C API in 1.2.0.)
- Breaking change: Reversed the order of the arguments to `createAppender`, in order to make both the schema and database/catalog optional.
- Fixed a bug in converting very large (>=2^64) negative hugeints to JS bigints.
- https://github.com/duckdb/duckdb-node-neo/pull/156
- …
=> bump pkgs to 1.2.0-alpha.15

bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts, bindings/src/duckdb_node_bindings.cpp, bindings/test/instance_cache.test.ts
Add bindings for `create_instance_cache` and `get_or_create_from_cache`. Not yet exposed at the API level.
=> bindings for instance cache

api/pkgs/@duckdb/node-api/package.json, api/src/createValue.ts, bindings/pkgs/@duckdb/node-bindings-darwin-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-x64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-x64/package.json, bindings/pkgs/@duckdb/node-bindings-win32-x64/package.json, bindings/pkgs/@duckdb/node-bindings/package.json, bindings/scripts/fetch_libduckdb_linux_aarch64.py, bindings/scripts/fetch_libduckdb_linux_amd64.py, bindings/scripts/fetch_libduckdb_osx_universal.py, bindings/scripts/fetch_libduckdb_windows_amd64.py, bindings/test/config.test.ts, bindings/test/constants.test.ts, bindings/test/prepared_statements.test.ts
Also bump package version to `alpha-16`. This version contains a couple additional changes:
- https://github.com/duckdb/duckdb-node-neo/pull/172
- https://github.com/duckdb/duckdb-node-neo/pull/174
=> update duckdb to 1.2.1

api/src/DuckDBInstance.ts, api/test/api.test.ts, bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts, bindings/src/duckdb_node_bindings.cpp, bindings/test/open.test.ts
Support closing an instance, using the same "holder" pattern used for supporting disconnecting connections.
=> instance close

api/src/DuckDBAppender.ts, api/src/DuckDBConnection.ts, api/src/DuckDBInstance.ts, api/test/api.test.ts, api/test/bench/write.bench.ts, bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts, bindings/src/duckdb_node_bindings.cpp, bindings/test/appender.test.ts, bindings/test/connection.test.ts, bindings/test/open.test.ts
- Add `Sync` suffix to close, disconnect, and flush methods that can perform significant work:
- instance.close -> instance.closeSync
- connection.close -> connection.closeSync
- connection.disconnect -> connection.disconnectSync
- appender.flush -> appender.flushSync
- appender.close -> appender.closeSync
- Add `_sync` suffix to corresponding bindings functions:
- close -> close_sync
- disconnect -> disconnect_sync
- appender_flush -> appender_flush_sync
- appender_close -> appender_close_sync
The implementation of these functions is unchanged.
In the future, I plan to add async versions of all of these, using the name without the `Sync` or `_sync` suffix. Releasing this name change separately from adding the async versions hopefully make migration easier, because the name change will be …
=> add sync to close, disconnect, and flush

api/pkgs/@duckdb/node-api/README.md, api/src/DuckDBResult.ts, api/src/DuckDBResultReader.ts, api/src/DuckDBType.ts, api/src/DuckDBValueToJsonConverter.ts, api/src/Json.ts, api/src/duckdb.ts, api/test/api.test.ts, api/test/util/testAllTypes.ts
Add functions to return column names and types as JSON, on both DuckDBResult and DuckDBResultReader:
- columnTypeJson(columnIndex)
- columnTypesJson()
- columnNamesAndTypesJson()
- columnNameAndTypeObjectsJson()
Add tests and documentation for the above.
=> column names and types json

api/src/DuckDBDataChunk.ts, api/src/getColumnsFromChunks.ts, api/src/getColumnsObjectFromChunks.ts, api/src/getRowObjectsFromChunks.ts, api/src/getRowsFromChunks.ts
Added getColumnsObject and getRowObjects to DuckDBDataChunk. These were incorrectly documented as existing, but didn't. The actual signatures differ somewhat from what was (incorrectly) documented - they need to take the list of column names, typically retrieved from result.deduplicatedColumnNames.
As part of this, factored out some related code into "append" methods that act on existing arrays or objects. This enabled some simplification of the functions that deal with arrays of chunks.
=> chunk objects methods

api/src/conversion/stringFromBlob.ts, api/test/bench/stringFromBlob.bench.ts
Benchmarked performance of two implementation of `stringFromBlob`. Determined that string concatenation is faster for smaller sizes (less than 2^16 bytes), on a MacBook Pro (M2 Max). Changed implementation to select faster path based on this threshold. See https://github.com/duckdb/duckdb-node-neo/pull/188
=> string from blob performance

api/pkgs/@duckdb/node-api/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-x64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-x64/package.json, bindings/pkgs/@duckdb/node-bindings-win32-x64/package.json, bindings/pkgs/@duckdb/node-bindings/package.json
- [instance cache in api](https://github.com/duckdb/duckdb-node-neo/commit/299e82e8301384876ade1dbb31876f71ac85b687)
- https://github.com/duckdb/duckdb-node-neo/pull/185
- https://github.com/duckdb/duckdb-node-neo/pull/186 (BREAKING: METHOD NAME CHANGES)
- https://github.com/duckdb/duckdb-node-neo/pull/187
- https://github.com/duckdb/duckdb-node-neo/pull/188 and https://github.com/duckdb/duckdb-node-neo/pull/194
- https://github.com/duckdb/duckdb-node-neo/pull/191
- https://github.com/duckdb/duckdb-node-neo/pull/192
- https://github.com/duckdb/duckdb-node-neo/pull/193
=> bump pkgs to 1.2.1-alpha.17

api/pkgs/@duckdb/node-api/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-x64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-x64/package.json, bindings/pkgs/@duckdb/node-bindings-win32-x64/package.json, bindings/pkgs/@duckdb/node-bindings/package.json, bindings/scripts/fetch_libduckdb_linux_aarch64.py, bindings/scripts/fetch_libduckdb_linux_amd64.py, bindings/scripts/fetch_libduckdb_osx_universal.py, bindings/scripts/fetch_libduckdb_windows_amd64.py, bindings/test/config.test.ts, bindings/test/constants.test.ts
Bump DuckDB to v1.2.2 and Node Neo to Alpha 18.
Only other changes in this version are some small README fixes.
=> upgrade to duckdb 1.2.2 and alpha 18

api/src/DuckDBPreparedStatement.ts, api/test/api.test.ts, bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts, bindings/src/duckdb_node_bindings.cpp, bindings/test/prepared_statements.test.ts
- Implement holder pattern for prepared statement external.
- Add `destroy_prepare_sync` to bindings.
- Add `destroySync` to `DuckDBPreparedStatement`.
Should provide a way to address #211.
=> add destroySync to DuckDBPreparedStatement

api/src/DuckDBDataChunk.ts, api/test/api.test.ts
Throw a friendly error if a data chunk's row count is set to larger than the max (2048).
See #205
=> data chunk: enforce max rows

api/src/DuckDBAppender.ts, api/src/DuckDBPreparedStatement.ts, api/test/api.test.ts
Add some type inference to make appending and binding arrays, lists, and structs easier.
See #182
=> append and bind type inference

api/src/DuckDBConnection.ts, api/src/DuckDBExtractedStatements.ts, api/src/DuckDBPreparedStatementCollection.ts, api/src/DuckDBPreparedStatementWeakRefCollection.ts, api/src/duckdb.ts
Hold on to WeakRefs of any prepared statements created on a connection, and destroy them when the connection is closed (if they still exist). This provides a more convenient and robust way to solve #211.
=> destroy prepared statements on connection close

README.md, api/pkgs/@duckdb/node-api/package.json, bindings/binding.gyp, bindings/pkgs/@duckdb/node-bindings-darwin-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-x64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-x64/package.json, bindings/pkgs/@duckdb/node-bindings-win32-x64/package.json, bindings/pkgs/@duckdb/node-bindings/package.json, bindings/scripts/checkFunctionSignatures.mjs, bindings/scripts/fetch_libduckdb_linux_aarch64.py, bindings/scripts/fetch_libduckdb_linux_amd64.py, bindings/scripts/fetch_libduckdb_linux_arm64.py, bindings/scripts/fetch_libduckdb_osx_universal.py, bindings/scripts/fetch_libduckdb_windows_amd64.py, bindings/test/appender.test.ts, bindings/test/config.test.ts, bindings/test/constants.test.ts
- New version is 1.3.0-alpha.20
- A couple minor test updates needed.
- C function prefix changed from DUCKDB_API to DUCKDB_C_API, necessitating minor changes to checkFunctionSignatures script.
- Linux aarch64 was renamed to Linux arm64, necessitating some build script changes.
=> upgrade to duckdb 1.3.0

api/pkgs/@duckdb/node-api/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-x64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-x64/package.json, bindings/pkgs/@duckdb/node-bindings-win32-x64/package.json, bindings/pkgs/@duckdb/node-bindings/package.json, bindings/scripts/fetch_libduckdb_linux_amd64.py, bindings/scripts/fetch_libduckdb_linux_arm64.py, bindings/scripts/fetch_libduckdb_osx_universal.py, bindings/scripts/fetch_libduckdb_windows_amd64.py, bindings/test/config.test.ts, bindings/test/constants.test.ts
Just the DuckDB patch version bump; no other changes.
=> upgrade to duckdb 1.3.2

api/pkgs/@duckdb/node-api/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-x64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-x64/package.json, bindings/pkgs/@duckdb/node-bindings-win32-x64/package.json, bindings/pkgs/@duckdb/node-bindings/package.json
This release contains a [fix](https://github.com/duckdb/duckdb-node-neo/pull/264) to a subtle [bug](https://github.com/duckdb/duckdb-node-neo/issues/257) that led to segmentation faults in certain cases. Thanks for the diagnosis & fix, @hrl20!
=> bump pkgs to 1.3.2-alpha.25

bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts, bindings/src/duckdb_node_bindings.cpp, bindings/test/scalar_functions.test.ts
Add bindings for the minimal subset of C API functions for using scalar functions.
=> core bindings for scalar functions

api/src/DuckDBPreparedStatementWeakRefCollection.ts, api/test/api.test.ts
Since the list of prepare statements weakrefs can get long when a process is create prepared statements at a high rate, only attempt to prune the list at most once a second. This should reduce the number of times we attempt to prune and fail to find any collected weakrefs.
=> throttle prepared pruning

bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts, bindings/src/duckdb_node_bindings.cpp, bindings/test/scalar_functions.test.ts
Support setting & getting "extra info" for a scalar function's main function.
Rather than using a separate function to set the extra info as in the C API, this is combined with setting the scalar function's function, because we need to use the actual extra info to hold the wrapper around the JS function. The user's extra info is held inside the actual extra info.
=> scalar func: main extra info

bindings/binding.gyp, bindings/src/duckdb_node_bindings.cpp
When running a scalar function, wrap the call to the JS function in an exception handler, and transform any error into an error in the scalar function.
The change to use `node_addon_api_except_all` instead of `node_addon_api_except` isn't strictly needed, but seems like a good idea in general to avoid crashing. (It should cause C++ exceptions to be converted to JS exceptions in more cases.)
=> scalar function exception handling

bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts, bindings/src/duckdb_node_bindings.cpp, bindings/test/scalar_functions.test.ts
Add support for scalar function parameters & varargs, as well as setting "volatile" and "special handling". Add tests.
Fix accounting comment; I missed updating it for a function I added earlier (`scalar_function_get_extra_info`).
=> scalar func args

bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts, bindings/src/duckdb_node_bindings.cpp, bindings/test/scalar_functions.test.ts
Refactor how scalar functions are implemented to support a separate `set_extra_info` function and set the stage for supporting the bind function & data.
Now, a reference to the internal extra info is stored by the holder, so the user extra info and function can be set in any order. Also, C++ objects are used to manage these internal data structures (instead of C memory management), simplifying things and avoiding some initialization pitfalls with the latter approach.
=> scalar function refactors

api/pkgs/@duckdb/node-api/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-darwin-x64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-arm64/package.json, bindings/pkgs/@duckdb/node-bindings-linux-x64/package.json, bindings/pkgs/@duckdb/node-bindings-win32-x64/package.json, bindings/pkgs/@duckdb/node-bindings/package.json
- Scalar function support
- See https://github.com/duckdb/duckdb-node-neo/pull/279 for API.
- Addresses #89.
- Not yet supported: bind functions. See #280.
- https://github.com/duckdb/duckdb-node-neo/pull/268
- Addresses #256
- https://github.com/duckdb/duckdb-node-neo/pull/269
- Addresses #263
=> bump pkgs to 1.3.2-alpha.26

api/src/sql.ts, api/test/api.test.ts
I discovered that the utility functions for quoting strings and identifiers only cover single instances of quotes. This PR adds tests and fixes the issue. Please let me know if you'd prefer any changes to this PR.
=> Fix quotedIdentifier and quotedString
