bindings/src/duckdb_node_bindings.cpp
bindings/test/prepared_statements.test.ts
bindings/test/values.test.ts

- use duckdb_free where needed
- values tests
- prepared statements tests (including nested types)

more tests

---

api/src/DuckDBExtractedStatements.ts
api/src/DuckDBPreparedStatement.ts
api/src/DuckDBResult.ts

- statement type & result return type to result
- statement type to prepared statement
- remove TODO comment that's not longer accurate

add statement type to api

---

bindings/.gitignore
bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts
bindings/src/duckdb_node_bindings.cpp
bindings/test/appender.test.ts
bindings/test/enums.test.ts
bindings/test/logical_type.test.ts
bindings/test/prepared_statements.test.ts
bindings/test/values.test.ts

- new types (ANY, VARINT, SQLNULL)
- bind timestamp_tz
- lots of new value functions (create, get, map)
- logical type set alias
- append default
- many comment placeholders for unimplemented types (mostly function creation)

updates for v1.1.1

---

.github/workflows/DuckDBNodeBindingsAndAPI.yml
api/pkgs/@duckdb/node-api/.npmrc
api/pkgs/@duckdb/node-api/package.json
bindings/pkgs/@duckdb/node-bindings-darwin-arm64/.npmrc
bindings/pkgs/@duckdb/node-bindings-darwin-arm64/package.json
bindings/pkgs/@duckdb/node-bindings-linux-x64/.npmrc
bindings/pkgs/@duckdb/node-bindings-linux-x64/package.json
bindings/pkgs/@duckdb/node-bindings-win32-x64/.npmrc
bindings/pkgs/@duckdb/node-bindings-win32-x64/package.json
bindings/pkgs/@duckdb/node-bindings/.npmrc
bindings/pkgs/@duckdb/node-bindings/package.json

Successfully published to NPM!

change package versions to 1.1.2-alpha.1

---

api/pkgs/@duckdb/node-api/README.md
api/src/DuckDBType.ts
api/src/index.ts
api/src/sql.ts
api/test/api.test.ts

Add `toString` methods to all data type objects.

data type toString

---

api/pkgs/@duckdb/node-api/README.md
api/src/DuckDBLogicalType.ts
api/src/DuckDBType.ts
api/src/DuckDBVector.ts
api/src/values/DuckDBBitValue.ts
api/src/values/DuckDBStructValue.ts
api/test/api.test.ts

- Change STRUCT and UNION types to have parallel arrays.
- Add various conversion methods to BIT value.
- Update README for API with detailed information about types and values, and also update Roadmap section.

change some types

---

api/src/DuckDBAppender.ts
api/src/DuckDBConnection.ts
api/src/DuckDBDataChunk.ts
api/src/DuckDBExtractedStatements.ts
api/src/DuckDBInstance.ts
api/src/DuckDBLogicalType.ts
api/src/DuckDBPendingResult.ts
api/src/DuckDBPreparedStatement.ts
api/src/DuckDBResult.ts
api/test/api.test.ts
api/test/bench/util/benchUtils.ts
api/test/bench/util/runSql.ts
bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts
bindings/src/duckdb_node_bindings.cpp
bindings/test/appender.test.ts
bindings/test/config.test.ts
bindings/test/data_chunk.test.ts
bindings/test/errors.test.ts
bindings/test/extracted_statements.test.ts
bindings/test/logical_type.test.ts
bindings/test/open.test.ts
bindings/test/pending.test.ts
bindings/test/prepared_statements.test.ts
bindings/test/query.test.ts
bindings/test/utils/expectResult.ts
bindings/test/utils/withConnection.ts
bindings/test/utils/withLogicalType.ts
bindings/test/values.test.ts

- Add finalizers to all Externals (except Vector).
- Remove all destroy methods (plus close and disconnect) from bindings.
- Remove all dispose methods from API.

finalizers

---

.github/workflows/DuckDBNodeBindingsAndAPI.yml
README.md
api/pkgs/@duckdb/node-api/README.md
bindings/binding.gyp
bindings/pkgs/@duckdb/node-bindings-darwin-x64/.npmrc
bindings/pkgs/@duckdb/node-bindings-darwin-x64/README.md
bindings/pkgs/@duckdb/node-bindings-darwin-x64/package.json
bindings/pkgs/@duckdb/node-bindings/README.md
bindings/pkgs/@duckdb/node-bindings/package.json
pnpm-lock.yaml

Add support for Mac OS X x64 (Intel).

support mac x64

---

api/src/conversion/dateTimeStringConversion.ts
api/src/values/DuckDBTimeTZValue.ts
api/src/values/DuckDBTimestampTZValue.ts
api/test/api.test.ts
api/test/util/testAllTypes.ts

Implement the timezone offset and seconds offset parts of TIMESTAMPTZ and TIMETZ `toString`.

fully implement TIMESTAMPTZ and TIMETZ toString

---

api/pkgs/@duckdb/node-api/package.json
bindings/pkgs/@duckdb/node-bindings-darwin-arm64/package.json
bindings/pkgs/@duckdb/node-bindings-darwin-x64/package.json
bindings/pkgs/@duckdb/node-bindings-linux-arm64/package.json
bindings/pkgs/@duckdb/node-bindings-linux-x64/package.json
bindings/pkgs/@duckdb/node-bindings-win32-x64/package.json
bindings/pkgs/@duckdb/node-bindings/package.json

Changes:
- https://github.com/duckdb/duckdb-node-neo/pull/127 (from @belgattitude)
- https://github.com/duckdb/duckdb-node-neo/pull/132
- https://github.com/duckdb/duckdb-node-neo/pull/135

bump pkgs to 1.1.3-alpha.12

---

api/pkgs/@duckdb/node-api/package.json
bindings/pkgs/@duckdb/node-bindings-darwin-arm64/package.json
bindings/pkgs/@duckdb/node-bindings-darwin-x64/package.json
bindings/pkgs/@duckdb/node-bindings-linux-arm64/package.json
bindings/pkgs/@duckdb/node-bindings-linux-x64/package.json
bindings/pkgs/@duckdb/node-bindings-win32-x64/package.json
bindings/pkgs/@duckdb/node-bindings/package.json

- https://github.com/duckdb/duckdb-node-neo/pull/144 (fixes https://github.com/duckdb/duckdb-node-neo/issues/142)
- https://github.com/duckdb/duckdb-node-neo/pull/147
- https://github.com/duckdb/duckdb-node-neo/pull/150
- https://github.com/duckdb/duckdb-node-neo/pull/152

bump pkgs to 1.2.0-alpha.14

---

.github/workflows/DuckDBNodeBindingsAndAPI.yml

Need to call `apt-get update`.

fix linux arm64 build

---

api/src/duckdb.ts
api/src/index.ts

See https://github.com/duckdb/duckdb-node-neo/issues/171

support default export in api in ts

---

api/src/conversion/stringFromBlob.ts

Changes related to the function:
- Wrong comments order
- Performance improvements

Changes in stringFromBlob function

---

api/pkgs/@duckdb/node-api/README.md
api/src/values/DuckDBBitValue.ts
api/src/values/DuckDBDateValue.ts
api/src/values/DuckDBDecimalValue.ts
api/src/values/DuckDBTimeValue.ts
api/src/values/DuckDBTimestampTZValue.ts
api/src/values/DuckDBTimestampValue.ts
bindings/pkgs/@duckdb/node-bindings-linux-arm64/README.md
bindings/pkgs/@duckdb/node-bindings/README.md

- Update README
- Document JS & custom converters.
- Fix documentation of chunk.getRowObjects and chunk.getColumnsObject.
- Document value creation functions.
- Remove "experimental" from Linux arm64 support.
- Add link to issues in Roadmap section.
- Improve value creation functions by accepting more types where appropriate.

readme updates & value creation function improvements

---

api/pkgs/@duckdb/node-api/package.json
bindings/pkgs/@duckdb/node-bindings-darwin-arm64/package.json
bindings/pkgs/@duckdb/node-bindings-darwin-x64/package.json
bindings/pkgs/@duckdb/node-bindings-linux-arm64/package.json
bindings/pkgs/@duckdb/node-bindings-linux-x64/package.json
bindings/pkgs/@duckdb/node-bindings-win32-x64/package.json
bindings/pkgs/@duckdb/node-bindings/package.json

- https://github.com/duckdb/duckdb-node-neo/pull/212
- fixes #211
- https://github.com/duckdb/duckdb-node-neo/pull/213
- addresses #205
- https://github.com/duckdb/duckdb-node-neo/pull/214
- addresses #182
- https://github.com/duckdb/duckdb-node-neo/pull/215
- https://github.com/duckdb/duckdb-node-neo/pull/217
- improves fix for #211

bump pkgs to 1.2.2-alpha.19

---

bindings/pkgs/@duckdb/node-bindings/duckdb.d.ts
bindings/src/duckdb_node_bindings.cpp
bindings/test/values.test.ts

Add new bindings functions:
- `create_map_value`
- `create_union_value`

create map and union value bindings

---

api/src/DuckDBConnection.ts
api/test/api.test.ts

Support running statements like PIVOT, that generate multiple statements behind the scenes, with parameters.
This uses `extractStatements` to generate the multiple statements and then runs all but the last, without parameters and ignoring results, before running the last with parameters. All modes of running are supported.

support running PIVOT with params

---

api/pkgs/@duckdb/node-api/package.json
bindings/pkgs/@duckdb/node-bindings-darwin-arm64/package.json
bindings/pkgs/@duckdb/node-bindings-darwin-x64/package.json
bindings/pkgs/@duckdb/node-bindings-linux-arm64/package.json
bindings/pkgs/@duckdb/node-bindings-linux-x64/package.json
bindings/pkgs/@duckdb/node-bindings-win32-x64/package.json
bindings/pkgs/@duckdb/node-bindings/package.json

Features in this version:
- https://github.com/duckdb/duckdb-node-neo/pull/244
- https://github.com/duckdb/duckdb-node-neo/pull/246
- https://github.com/duckdb/duckdb-node-neo/pull/249

bump pkgs to 1.3.1-alpha.23

---

.gitignore
api/pkgs/@duckdb/node-api/package.json
bindings/pkgs/@duckdb/node-bindings-darwin-arm64/package.json
bindings/pkgs/@duckdb/node-bindings-darwin-x64/package.json
bindings/pkgs/@duckdb/node-bindings-linux-arm64/package.json
bindings/pkgs/@duckdb/node-bindings-linux-x64/package.json
bindings/pkgs/@duckdb/node-bindings-win32-x64/package.json
bindings/pkgs/@duckdb/node-bindings/package.json

Notable changes:
* https://github.com/duckdb/duckdb-node-neo/pull/303

bump versions to release 1.4.0-r.2
